version: "3.9"
services:
  udacity-ai-trading:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/home/jovyan/work'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - "10000:8888"



